# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/docs/getting-started/configuration/#menu-configuration
# -------------------------------------------------------------------------------------
# 说明：本文件内容等价于 [menus] + [[menus.main]]，Hugo 会按文件名把根键映射为 menus。

[[main]]
identifier = "home"
name = "主页"
url = "/"
weight = 10

[main.params]
icon = "fa-solid fa-house"

[[main]]
identifier = "archives"
name = "归档"
url = "/post/"
weight = 20

[main.params]
icon = "fa-solid fa-archive"

[[main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 30

[main.params]
icon = "fa-solid fa-tags"

[[main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 40

[main.params]
icon = "fa-solid fa-folder-tree"

[[main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 50

[main.params]
icon = "fa-solid fa-circle-info"

